<a href="https://colab.research.google.com/github/DivyaBharsakle/EDS_342_Divya-Bharsakle/blob/main/Untitled16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data=pd.read_csv("/content/coffee (1).csv")
print(data.shape)
data.head()

(34, 12)

,Country of Origin,Number of Bags,Bag Weight,Aroma,Flavor,Aftertaste,Acidity,Balance,Sweetness,Moisture Percentage,Color,Category Two Defects
0,Colombia,1,35 kg,8.58,8.50,8.42,8.58,8.42,10,11.8,green,3
1,Taiwan,1,80 kg,8.50,8.50,7.92,8.00,8.25,10,10.5,blue-green,0
2,Laos,19,25 kg,8.33,8.42,8.08,8.17,8.17,10,10.4,yellowish,2
3,Costa Rica,1,22 kg,8.08,8.17,8.17,8.25,8.08,10,11.8,green,0
4,Colombia,2,24 kg,8.33,8.33,8.08,8.25,7.92,10,11.6,yellow-green,2